### ISSUE TITLE
Error: spawn casperjs ENOENT on running casper locally

### ISSUE THREAD

**Issue by vyscond** [NullRefExcep/gulp-casperjs#8]
Got this error

```
$ gulp casper
[15:04:35] Using gulpfile ~/Development/alpha/gulpfile.js
[15:04:35] Starting 'casper'...
[15:04:35] Finished 'casper' after 8.88 ms
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn casperjs ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

Seems that the plugin cannot execute casper if it is installed locally .-. any thoughts?

**Comment by ZAYEC77** [comment]
@vyscond Hello, yes, you right, casper must be installed globally

**Comment by vyscond** [comment]
Is impossible to achieve the same experience with local install?

**Comment by ZAYEC77** [comment]
@vyscond can you give example how you run local version of casper?
(I'm talk about shell command)

**Comment by vyscond** [comment]
Running as indicated on the site `node_modules/casperjs/bin/casperjs selftest`

**Comment by ZAYEC77** [comment]
@vyscond what do you think about parameter e.g:
```js
gulp.task('test', function () {
  gulp.src('./test.js')
    .pipe(casperJs({
    	binPath: './node_modules/casperjs/bin/casperjs'
    })); 
});
```

It will be comfort for you?

**Comment by ZAYEC77** [comment]
@vyscond please, checkout new version of plugin.

**Comment by vyscond** [comment]
I think this far better than i planned. Flexible, readable and intuitive. I will check the new version tonight! Thanks for making this update so quickly.

**Comment by vyscond** [comment]
Got this error

```
[15:20:24] Starting 'casper'...
[15:20:24] 'casper' errored after 8.76 ms
[15:20:24] TypeError: dest.on is not a function
    at DestroyableTransform.Readable.pipe (/var/www/projects/alpha/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:516:8)
    at Gulp.<anonymous> (/var/www/projects/alpha/gulpfile.js:13:23)
    at module.exports (/var/www/projects/alpha/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/var/www/projects/alpha/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/var/www/projects/alpha/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/var/www/projects/alpha/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:46:20
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
```

**Comment by vyscond** [comment]
Working flawlessly. Thank you.

**Comment by ZAYEC77** [comment]
@vyscond thanks for feedback
